---
title: LED-vuurvlieg
hero_image: images/banner.png
description:
  - Use a Raspberry Pi Pico to make an LED firefly that flashes in a particular pattern, just like fireflies in nature
  - pattern, just like fireflies in nature
meta_title: Raspberry Pi Pico projects | LED firefly
meta_description: A Raspberry Pi Pico project to make an LED firefly that flashes in a particular pattern, just like fireflies in nature.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: You will make
  - 
    title: Stel je Raspberry Pi Pico in
  - 
    title: Steek de Raspberry Pi Pico LED aan
    completion:
      - engaged
  - 
    title: Steek je vuurvlieg aan
  - 
    title: Laat je vuurvlieg knipperen
  - 
    title: Voeg een schakelaar toe
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Verbeter je project
  - 
    title: Wat kun je verder nog doen?
